name: 'deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: install && build
        run: npm install && npm run build
        
      - name: upload file
        uses: appleboy/scp-action@v0.0.1
        with: 
          host: ${{ HOST }}
          username: ${{ USERNAME }}
          password: ${{ PASSWORD }}
          port: 22
          source: "/dist"
          target: ${{ TARGET }}
    
